spring:
  datasource:
    url: jdbc:mysql://localhost:3306/beetgott
    username: AlexDur
    password: Hophophop3!
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
server:
  error:
    path: /error
